### ISSUE TITLE
Normalize whitespace before commit

### ISSUE THREAD

**Issue by denys-potapov** [scharwerk/scharwerk#17]
Normalise whitespace should work standalone and executed before each text commit:
- Replace tabs (\t) with 4 spaces
- Remove trailing whitespaces
- Normalise lineendings (\n)
- Add empty line at end of file (if there is no empty line)

**Comment by hmasila** [comment]
Hey @denys-potapov I would like to do this. Is there a particular file you want the changes to take place or the entire project?

**Comment by denys-potapov** [comment]
@hmasila thanks for the reply, but this issue is already assigned. Sorry.
