### ISSUE TITLE
In stats replace tasks count with pages count

### ISSUE THREAD

**Issue by denys-potapov** [scharwerk/scharwerk#18]
1. Remove from stats users that have no tasks done
2. Replace users::tasks_done with users::pages_done `tasks.commited.pages.count`

**Comment by sundus-y** [comment]
i will take a crack at it

**Comment by sundus-y** [comment]
@chmen & @denys-potapov Sorry didn't notice it was already assigned.

**Comment by denys-potapov** [comment]
hi, @sundus-y you can take it. If you have question do not hesitate to write it.

Currently the stats contsoller::users returns done, and going. The going should be removed, and the done users stats replaced with pages count in done tasks. You can look at app live at http://шарварок.маркс.укр/

**Comment by sundus-y** [comment]
@denys-potapov Are there any seed data that I can use to run the app with?

**Comment by denys-potapov** [comment]
This is backup from production DB - https://www.dropbox.com/s/o6yj0knik12r205/backup.22.10.psql?dl=0

You can restore it with pg_restore -d dbname filename
